name: tests

on: [push, pull_request]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install boost
      uses: MarkusJx/install-boost@v2
      id: install-boost
      with:
        # REQUIRED: Specify the required boost version
        # A list of supported versions can be found here:
        # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
        boost_version: 1.84.0
        # OPTIONAL: Specify a platform version
        platform_version: 22.04
        # OPTIONAL: Specify a custom install location
        boost_install_dir: /home/runner/
        # OPTIONAL: Specify a toolset
        toolset: gcc
        # OPTIONAL: Specify an architecture
        arch: x86

    - name: Init Git Submodules
      run: git submodule update --init

    - name: Configure CMake
      run: make cmake-debug
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        CXXFLAGS: "-I${{ steps.install-boost.outputs.BOOST_ROOT }}/include"

    - name: Build
      run: make build-debug

    - name: Test
      run: make tests
